on:
  workflow_dispatch:
  schedule:
    - cron: '45 12,14,16,18,20,22 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-1@cron
        with:
          token: ${{ secrets.token }}
